import {useEffect,useRef,useState, type FormEvent} from 'react';
import L from 'leaflet';
import {useReducedMotion} from 'framer-motion';
import type {Observation} from '../../ai/thermalEngine';
import boundary from '../../data/indiaBoundary.json';
import type {GeoJsonObject} from 'geojson';
import 'leaflet/dist/leaflet.css';

type PlaceResult={place_id:number;display_name:string;lat:string;lon:string;type?:string};
const placeCache=new Map<string,PlaceResult[]>();
let lastPlaceRequest=0;
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

export default function ObservationMap({observations,selected,onSelect,onLocation}:{observations:Observation[];selected:Observation|null;onSelect:(observation:Observation)=>void;onLocation?:(point:{latitude:number;longitude:number})=>void}){
 const locationCallback=useRef(onLocation);locationCallback.current=onLocation;
 const host=useRef<HTMLDivElement>(null);const map=useRef<L.Map|null>(null);const layer=useRef<L.LayerGroup|null>(null);const marker=useRef<L.CircleMarker|null>(null);const searchMarker=useRef<L.CircleMarker|null>(null);const previous=useRef<string|null>(null);const tiles=useRef<L.TileLayer|null>(null);const [tileError,setTileError]=useState(false);const callback=useRef(onSelect);callback.current=onSelect;const reduced=useReducedMotion();
 const [placeQuery,setPlaceQuery]=useState('');const [placeResults,setPlaceResults]=useState<PlaceResult[]>([]);const [placeStatus,setPlaceStatus]=useState('');const [placeLoading,setPlaceLoading]=useState(false);
 useEffect(()=>{if(!host.current)return;const instance=L.map(host.current,{preferCanvas:true,scrollWheelZoom:false,minZoom:3,maxZoom:18,zoomAnimation:!reduced,fadeAnimation:!reduced}).fitBounds([[6,67],[38,99]]);map.current=instance;instance.on('click',event=>locationCallback.current?.({latitude:event.latlng.lat,longitude:event.latlng.lng}));instance.attributionControl.setPrefix(false);const tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(instance);tiles.current=tileLayer;tileLayer.on('tileerror',()=>setTileError(true));L.geoJSON(boundary as GeoJsonObject,{interactive:false,style:{color:'#7e9fba',weight:1,fillOpacity:.03}}).addTo(instance);layer.current=L.layerGroup().addTo(instance);const resize=new ResizeObserver(()=>instance.invalidateSize({pan:false}));resize.observe(host.current);return()=>{resize.disconnect();tileLayer.off();instance.remove();map.current=null;tiles.current=null;layer.current=null;marker.current=null;searchMarker.current=null;previous.current=null;};},[]);
 useEffect(()=>{const instance=map.current;const group=layer.current;if(!instance||!group)return;group.clearLayers();for(const observation of observations){const dot=L.circleMarker([observation.latitude,observation.longitude],{bubblingMouseEvents:false,radius:4,color:observation.source==='demo'?'#92b9df':'#edb77a',weight:1,fillOpacity:.65});const tooltip=document.createElement('div');tooltip.textContent=`${observation.frp} MW / ${new Date(observation.observedAt).toLocaleString()} / ${observation.source}`;dot.bindTooltip(tooltip);dot.on('click',()=>callback.current(observation));group.addLayer(dot);}},[observations]);
 useEffect(()=>{const instance=map.current;if(!instance)return;marker.current?.remove();marker.current=null;if(!selected)return;marker.current=L.circleMarker([selected.latitude,selected.longitude],{radius:10,color:'#fff1d7',weight:2,fillColor:'#e6b477',fillOpacity:.25,interactive:false}).addTo(instance);const outsideIndia=selected.latitude<6||selected.latitude>38||selected.longitude<67||selected.longitude>99;if((previous.current&&previous.current!==selected.id)||outsideIndia)instance.setView([selected.latitude,selected.longitude],Math.max(instance.getZoom(),10),{animate:!reduced});previous.current=selected.id;},[selected,reduced]);
 async function searchPlace(event:FormEvent<HTMLFormElement>){event.preventDefault();const query=placeQuery.trim();if(query.length<2){setPlaceResults([]);setPlaceStatus('Enter at least 2 characters, for example “Nagpur” or “Bhilai Steel Plant”.');return;}setPlaceLoading(true);setPlaceStatus('Searching India…');try{const key=query.toLowerCase();let results=placeCache.get(key);if(!results){const wait=Math.max(0,1100-(Date.now()-lastPlaceRequest));if(wait)await sleep(wait);lastPlaceRequest=Date.now();const params=new URLSearchParams({format:'jsonv2',countrycodes:'in',limit:'5',addressdetails:'1',q:query});const response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Place search provider unavailable');const raw=await response.json();results=Array.isArray(raw)?raw.filter((item:PlaceResult)=>{const lat=Number(item.lat),lon=Number(item.lon);return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=6&&lat<=38&&lon>=67&&lon<=99;}).slice(0,5):[];placeCache.set(key,results);}setPlaceResults(results);setPlaceStatus(results.length?'Choose a result to inspect nearby NASA detections.':'No matching India location found. Try a city, district, landmark or facility name.');}catch{setPlaceResults([]);setPlaceStatus('Place search could not load. You can still click the map or enter latitude/longitude below.');}finally{setPlaceLoading(false);}}
 function usePlace(result:PlaceResult){const latitude=Number(result.lat),longitude=Number(result.lon);if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return;searchMarker.current?.remove();searchMarker.current=L.circleMarker([latitude,longitude],{radius:9,color:'#ffffff',weight:2,fillColor:'#92b9df',fillOpacity:.35,interactive:false}).addTo(map.current!);map.current?.setView([latitude,longitude],11,{animate:!reduced});locationCallback.current?.({latitude,longitude});setPlaceStatus(`Exploring ${result.display_name}. AGNITE will use NASA detections within 5 km when available.`);}
 return <>
  <form className="ws-form" onSubmit={searchPlace} style={{marginBottom:'1rem'}}><label className="ws-full">Search a place in India<input type="search" value={placeQuery} onChange={event=>setPlaceQuery(event.target.value)} placeholder="e.g. Nagpur, Dehradun, Bhilai Steel Plant" maxLength={120}/></label><div className="ws-actions ws-full"><button className="ws-button primary" type="submit" disabled={placeLoading}>{placeLoading?'Searching…':'Search location'}</button></div></form>
  {placeStatus&&<p role="status" className="ws-source">{placeStatus}</p>}
  {placeResults.length>0&&<div className="ws-list" style={{marginBottom:'1rem'}}>{placeResults.map(result=><article className="ws-list-item" key={result.place_id}><div><strong>{result.display_name}</strong>{result.type&&<p>{result.type}</p>}</div><button className="ws-button" type="button" onClick={()=>usePlace(result)}>Use location</button></article>)}</div>}
  <div className="ws-map-frame"><div ref={host} className="ws-map" role="region" aria-label="Thermal observation map. Select a detection, search a place, or use the accessible observation list."/><button className="ws-map-reset" onClick={()=>map.current?.fitBounds([[6,67],[38,99]],{animate:!reduced})}>India region</button></div>
  {tileError&&<div className="ws-notice" role="status">Some street tiles could not load. Observations and the outline remain available.<button onClick={()=>{setTileError(false);tiles.current?.redraw();}}>Retry map tiles</button></div>}
  <p className="ws-source">Place search © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a> via Nominatim. Search runs only when you press the button; results are cached in this page.</p>
 </>;
}
