import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import {useReducedMotion} from 'framer-motion';
import type {Observation} from '../../ai/thermalEngine';
import boundary from '../../data/indiaBoundary.json';
import type {GeoJsonObject} from 'geojson';
import 'leaflet/dist/leaflet.css';
export default function ObservationMap({observations,selected,onSelect,onLocation}:{observations:Observation[];selected:Observation|null;onSelect:(observation:Observation)=>void;onLocation?:(point:{latitude:number;longitude:number})=>void}){
 const locationCallback=useRef(onLocation);locationCallback.current=onLocation;
 const host=useRef<HTMLDivElement>(null);const map=useRef<L.Map|null>(null);const layer=useRef<L.LayerGroup|null>(null);const marker=useRef<L.CircleMarker|null>(null);const previous=useRef<string|null>(null);const tiles=useRef<L.TileLayer|null>(null);const [tileError,setTileError]=useState(false);const callback=useRef(onSelect);callback.current=onSelect;const reduced=useReducedMotion();
 useEffect(()=>{if(!host.current)return;const instance=L.map(host.current,{preferCanvas:true,scrollWheelZoom:false,minZoom:3,maxZoom:18,zoomAnimation:!reduced,fadeAnimation:!reduced}).fitBounds([[6,67],[38,99]]);map.current=instance;instance.on('click',event=>locationCallback.current?.({latitude:event.latlng.lat,longitude:event.latlng.lng}));instance.attributionControl.setPrefix(false);const tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(instance);tiles.current=tileLayer;tileLayer.on('tileerror',()=>setTileError(true));L.geoJSON(boundary as GeoJsonObject,{interactive:false,style:{color:'#7e9fba',weight:1,fillOpacity:.03}}).addTo(instance);layer.current=L.layerGroup().addTo(instance);const resize=new ResizeObserver(()=>instance.invalidateSize({pan:false}));resize.observe(host.current);return()=>{resize.disconnect();tileLayer.off();instance.remove();map.current=null;tiles.current=null;layer.current=null;marker.current=null;previous.current=null;};},[]);
 useEffect(()=>{const instance=map.current;const group=layer.current;if(!instance||!group)return;group.clearLayers();for(const observation of observations){const dot=L.circleMarker([observation.latitude,observation.longitude],{bubblingMouseEvents:false,radius:4,color:observation.source==='demo'?'#92b9df':'#edb77a',weight:1,fillOpacity:.65});const tooltip=document.createElement('div');tooltip.textContent=`${observation.frp} MW / ${new Date(observation.observedAt).toLocaleString()} / ${observation.source}`;dot.bindTooltip(tooltip);dot.on('click',()=>callback.current(observation));group.addLayer(dot);}},[observations]);
 useEffect(()=>{const instance=map.current;if(!instance)return;marker.current?.remove();marker.current=null;if(!selected)return;marker.current=L.circleMarker([selected.latitude,selected.longitude],{radius:10,color:'#fff1d7',weight:2,fillColor:'#e6b477',fillOpacity:.25,interactive:false}).addTo(instance);const outsideIndia=selected.latitude<6||selected.latitude>38||selected.longitude<67||selected.longitude>99;if((previous.current&&previous.current!==selected.id)||outsideIndia)instance.setView([selected.latitude,selected.longitude],Math.max(instance.getZoom(),10),{animate:!reduced});previous.current=selected.id;},[selected,reduced]);
 return <><div className="ws-map-frame"><div ref={host} className="ws-map" role="region" aria-label="Thermal observation map. Select a detection or use the accessible observation list."/><button className="ws-map-reset" onClick={()=>map.current?.fitBounds([[6,67],[38,99]],{animate:!reduced})}>India region</button></div>{tileError&&<div className="ws-notice" role="status">Some street tiles could not load. Observations and the outline remain available.<button onClick={()=>{setTileError(false);tiles.current?.redraw();}}>Retry map tiles</button></div>}</>;
}
