import {useEffect,useMemo,useRef,useState, type FormEvent} from 'react';
import {Activity, ArrowLeft, Bell, BrainCircuit, Download, Flame, History, MessageSquare, RefreshCw, Satellite, Send, Trash2, Upload} from 'lucide-react';
import ObservationMap from '../components/workspace/ObservationMap';
import AnalysisPanel from '../components/workspace/AnalysisPanel';
import {useFirmsFeed} from '../hooks/useFirmsFeed';
import {analyzeObservations, validateObservations, type AnalysisContext, type AnalysisResult, type Observation} from '../ai/thermalEngine';
import {runAnalysis} from '../services/analysisApi';
import {parseObservationCsv,exportObservationsCsv,MAX_IMPORT_BYTES,type ObservationImportResult} from '../ai/observationImport';
import {distanceKm,downloadText,isSavedReport,isWatch,readSaved,sampleObservations,type SavedReport,type WatchLocation} from '../ai/workspaceData';
import {answerQuestion} from '../ai/localAssistant';
import {saveReportBackend, fetchReportsBackend, deleteReportBackend} from '../services/reportApi';
import {createWatchBackend, fetchWatchesBackend, deleteWatchBackend} from '../services/monitoringApi';
import '../styles/workspace.css';

const tabs=[{id:'feed',label:'Satellite feed',icon:Satellite},{id:'analysis',label:'AGNITE AI',icon:BrainCircuit},{id:'monitoring',label:'Monitoring',icon:Bell},{id:'history',label:'Saved reports',icon:History},{id:'import',label:'Import data',icon:Upload},{id:'assistant',label:'Ask AGNITE',icon:MessageSquare}] as const;
type Tab=typeof tabs[number]['id'];
const initialContext:AnalysisContext={landCover:'unknown',industrialDistanceKm:null,windKph:null};
const time=(value:string|null|undefined)=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
const coord=(row:{latitude:number;longitude:number})=>`${row.latitude.toFixed(4)}, ${row.longitude.toFixed(4)}`;
const getTab=():Tab=>{const value=new URLSearchParams(window.location.hash.split('?')[1]).get('tab');return tabs.find(tab=>tab.id===value)?.id||'feed';};

export default function Workspace(){
 const [tab,setTab]=useState<Tab>(getTab);
 const [sensor,setSensor]=useState('noaa20');const [hours,setHours]=useState(24);const [automatic,setAutomatic]=useState(true);
 const {feed,loading,error,refresh}=useFirmsFeed(sensor,hours,automatic);
 const [mode,setMode]=useState<'live'|'local'>('live');const [local,setLocal]=useState<Observation[]>([]);const [selectedId,setSelectedId]=useState('');
 const [search,setSearch]=useState('');const [minimum,setMinimum]=useState('');const [sort,setSort]=useState('latest');const [page,setPage]=useState(0);
 const [context,setContext]=useState<AnalysisContext>(initialContext);const [report,setReport]=useState<AnalysisResult|null>(null);const [notice,setNotice]=useState('');const [actionError,setActionError]=useState('');
 const [reports,setReports]=useState(()=>readSaved<SavedReport>('agnite.reports.v1',isSavedReport));const [watches,setWatches]=useState(()=>readSaved<WatchLocation>('agnite.watches.v1',isWatch));
 const [watchName,setWatchName]=useState('');const [threshold,setThreshold]=useState('20');
 const [csv,setCsv]=useState<ObservationImportResult|null>(null);const [fileName,setFileName]=useState('');const importRequest=useRef(0);
 const [question,setQuestion]=useState('');const [messages,setMessages]=useState<{role:'user'|'assistant';text:string}[]>([{role:'assistant',text:'I can inspect loaded observations and explain your latest analysis. Ask about the highest FRP, evidence, classification or monitoring.'}]);
 const observations=useMemo(()=>mode==='live'?(feed?.observations??[]):local,[mode,feed,local]);
 const selected=useMemo(()=>selectedId?(observations.find(row=>row.id===selectedId)||null):(observations[0]||null),[observations,selectedId]);
 const nearby=useMemo(()=>selected?observations.filter(row=>distanceKm(row,selected)<=5):[],[observations,selected]);
 const visible=useMemo(()=>observations.filter(row=>(minimum===''||row.frp>=Number(minimum))&&`${coord(row)} ${row.id} ${row.observedAt}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='frp'?b.frp-a.frp:Date.parse(b.observedAt)-Date.parse(a.observedAt)),[observations,minimum,search,sort]);
 const totalPages=Math.max(1,Math.ceil(visible.length/10));const safePage=Math.min(page,totalPages-1);const pageRows=visible.slice(safePage*10,safePage*10+10);
 const highest=useMemo(()=>observations.reduce((max,row)=>Math.max(max,row.frp),0),[observations]);
 const alerts=useMemo(()=>watches.map(watch=>({watch,matches:(feed?.observations??[]).filter(row=>distanceKm(row,watch)<=5&&row.frp>=watch.threshold)})),[watches,feed]);
 useEffect(()=>{const listener=()=>setTab(getTab());window.addEventListener('hashchange',listener);document.title='AGNITE | Thermal Intelligence Workspace';window.scrollTo(0,0);return()=>{window.removeEventListener('hashchange',listener);document.title='AGNITE | AI-Powered Thermal Intelligence';};},[]);
 useEffect(()=>{
  fetchReportsBackend().then(serverReports=>{
   if(serverReports&&serverReports.length>0){
    setReports(prev=>{
     const ids=new Set(serverReports.map(r=>r.id));
     return [...serverReports,...prev.filter(r=>!ids.has(r.id))].slice(0,50);
    });
   }
  }).catch(()=>{/* quiet fallback */});
  fetchWatchesBackend().then(serverWatches=>{
   if(serverWatches&&serverWatches.length>0){
    setWatches(prev=>{
     const ids=new Set(serverWatches.map(w=>w.id));
     return [...serverWatches,...prev.filter(w=>!ids.has(w.id))].slice(0,50);
    });
   }
  }).catch(()=>{/* quiet fallback */});
 },[]);
 useEffect(()=>{setReport(null);},[selected,observations,context]);
 useEffect(()=>{if(!selectedId&&observations.length)setSelectedId(observations[0].id);},[observations,selectedId]);
 useEffect(()=>{setPage(0);},[search,minimum,sort,mode,sensor,hours]);
 function navigate(next:Tab){setTab(next);window.location.hash=`/workspace?tab=${next}`;setActionError('');}
 function persist<T>(key:string,items:T[],update:(items:T[])=>void){try{localStorage.setItem(key,JSON.stringify(items));update(items);return true;}catch{setActionError('Browser storage is unavailable or full. Export a JSON copy instead.');return false;}}
 function choose(row:Observation){setSelectedId(row.id);setReport(null);setContext(initialContext);}
 function activate(data:Observation[],demo=false){setLocal(data);setMode('local');setSelectedId(data[data.length-1]?.id??'');setReport(null);setContext(demo?{landCover:'industrial',industrialDistanceKm:.5,windKph:12}:initialContext);setSearch('');setMinimum('');}
 function loadDemo(){activate(sampleObservations(),true);setNotice('Synthetic demo loaded. All observations and supplied context in this scenario are simulated.');navigate('analysis');}
 async function run(){setActionError('');try{const result=await runAnalysis({selectedObservation:selected,observations,radiusKm:5,context});setReport(result);}catch(backendErr){console.warn('Backend analysis failed, using local fallback:',backendErr);try{setReport(analyzeObservations(nearby,context,selected??undefined));setNotice('Using local fallback analysis because backend intelligence is unavailable.');}catch(reason){setActionError(reason instanceof Error?reason.message:'Analysis failed.');}}}
 async function save(){if(!report||!selected)return;const entry:SavedReport={id:crypto.randomUUID(),createdAt:new Date().toISOString(),label:coord(report.statistics.center),classification:report.classification,risk:report.risk.index,summary:report.summary,report,context,observations:nearby};persist('agnite.reports.v1',[entry,...reports].slice(0,50),setReports);setNotice('Report saved in archive.');try{await saveReportBackend(entry);setNotice('Report saved to backend persistent database and local archive.');}catch{/* backend unavailable, local saved */}}
 async function addWatch(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const value=Number(threshold);if(!watchName.trim()||!Number.isFinite(value)||value<0||value>1000000){setActionError('Enter a location name and an FRP threshold from 0 to 1,000,000 MW.');return;}if(watches.length>=50){setActionError('This browser supports up to 50 monitored sites. Remove a site before adding another.');return;}const newWatch:WatchLocation={id:crypto.randomUUID(),name:watchName.trim(),latitude:selected.latitude,longitude:selected.longitude,threshold:value};persist('agnite.watches.v1',[...watches,newWatch],setWatches);setNotice('Location saved. Matching observations from the loaded NASA feed appear below.');const savedName=watchName.trim();setWatchName('');try{const serverWatch=await createWatchBackend({name:savedName,latitude:selected.latitude,longitude:selected.longitude,threshold:value});setWatches(curr=>curr.map(w=>w.id===newWatch.id?{...w,id:serverWatch.id}:w));}catch{/* local fallback */}}
 function removeWatch(watch:WatchLocation){persist('agnite.watches.v1',watches.filter(item=>item.id!==watch.id),setWatches);deleteWatchBackend(watch.id).catch(()=>{});}
 function removeReport(item:SavedReport){persist('agnite.reports.v1',reports.filter(row=>row.id!==item.id),setReports);deleteReportBackend(item.id).catch(()=>{});}
 async function importFile(file:File|undefined){const request=++importRequest.current;setCsv(null);setActionError('');if(!file)return;setFileName(file.name);if(file.size>MAX_IMPORT_BYTES){setActionError('CSV must be 2 MB or smaller.');return;}try{const text=await file.text();if(request===importRequest.current)setCsv(parseObservationCsv(text));}catch{if(request===importRequest.current)setActionError('The file could not be read. Choose a UTF-8 CSV.');}}
 function manual(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{const observedAt=new Date(`${data.get('date')}:00Z`).toISOString();const row:Observation={id:`MANUAL-${crypto.randomUUID()}`,latitude:Number(data.get('latitude')),longitude:Number(data.get('longitude')),observedAt,frp:Number(data.get('frp')),source:'manual'};validateObservations([row]);const existing=mode==='local'?local.filter(item=>item.source!=='demo'):[];if(existing.length>=5000)throw new Error('Use at most 5,000 local observations.');activate([...existing,row]);setNotice('Manual observation added. Add repeated passes at the same location to build history.');form.reset();}catch(reason){setActionError(reason instanceof Error?reason.message:'Check the observation fields.');}}
 function ask(text:string){if(!text.trim())return;setMessages(current=>[...current,{role:'user' as const,text:text.trim()},{role:'assistant' as const,text:answerQuestion(text,observations,report)}].slice(-40));setQuestion('');}

 return <div className="workspace">
  <header className="ws-topbar"><a href="#home" className="brand"><Flame className="brand-mark" size={29}/><span><strong>AGNITE</strong><small>THERMAL INTELLIGENCE WORKSPACE</small></span></a><div className="ws-actions"><span className={`ws-status ${feed&&!error&&!feed.stale?'online':'warning'}`}><i/>{loading?'CHECKING NASA':error?'FEED UNAVAILABLE':feed?.stale?'CACHED NASA DATA':feed?'NASA FIRMS / NRT':'CONNECTING'}</span><a href="#home" className="ws-button subtle"><ArrowLeft size={15}/> Overview</a></div></header>
  <div className="ws-shell"><aside className="ws-sidebar"><span className="ws-kicker">MISSION WORKSPACE</span><nav className="ws-nav" aria-label="Workspace navigation">{tabs.map(item=><button key={item.id} className={tab===item.id?'active':''} aria-current={tab===item.id?'page':undefined} onClick={()=>navigate(item.id)}><item.icon size={18}/>{item.label}{item.id==='history'&&reports.length>0&&<small>{reports.length}</small>}</button>)}</nav><div className="ws-source"><Activity size={17}/><p>Satellite detections.<br/>Traceable evidence.<br/>Context-aware analysis.</p><a href="https://firms.modaps.eosdis.nasa.gov/active_fire/" target="_blank" rel="noreferrer">NASA FIRMS documentation ↗</a></div></aside>
  <main className="ws-main"><div className="ws-panel-head"><div><span className="ws-kicker">INDIA REGION / {tab==='analysis'?'EXPLAINABLE ANALYSIS':'THERMAL OBSERVATIONS'}</span><h1 className="ws-title">{tabs.find(item=>item.id===tab)?.label}</h1></div><span className={`ws-status ${mode==='local'?'warning':''}`}>{mode==='live'?'NASA DATA':local.some(row=>row.source==='demo')?'SIMULATED DATA':'LOCAL DATA'}</span></div>
   <p className="ws-subtitle">{tab==='feed'?'Explore satellite detections, select a site and follow its evidence. Acquisition times reflect satellite passes, not continuous surveillance.':tab==='analysis'?'Understand the observed signal, historical baseline and limits of the available evidence.':tab==='monitoring'?'Monitor saved coordinates against the latest loaded NASA observations.':tab==='history'?'Your saved analysis snapshots, stored in this browser.':tab==='import'?'Bring your own observations for local analysis. CSV contents stay in this browser.':'A local assistant grounded in the current dataset and analysis report.'}</p>
   {notice&&<div className="ws-notice success" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
   {actionError&&<div className="ws-notice error" role="alert">{actionError}<button onClick={()=>setActionError('')} aria-label="Dismiss error">×</button></div>}
   {error&&<div className="ws-notice error" role="alert">NASA feed unavailable: {error} {feed?'Previously loaded observations remain visible with their original timestamps.':'No live observations have been substituted.'}<button onClick={()=>void refresh()}>Retry</button></div>}
   {mode==='local'&&tab!=='history'&&<div className="ws-notice">{local.some(row=>row.source==='demo')?'This dataset includes simulated observations.':'You are viewing imported or manually entered data.'}<button onClick={()=>{setMode('live');setSelectedId('');setContext(initialContext);}}>Return to NASA feed</button></div>}

   {tab==='feed'&&<>
    <div className="ws-toolbar"><label>Sensor<select value={sensor} onChange={e=>{setSensor(e.target.value);setMode('live');setSelectedId('');setContext(initialContext);}}><option value="noaa20">VIIRS · NOAA-20</option><option value="snpp">VIIRS · Suomi NPP</option><option value="modis">MODIS · Terra / Aqua</option></select></label><label>Observation window<select value={hours} onChange={e=>{setHours(Number(e.target.value));setMode('live');setSelectedId('');setContext(initialContext);}}><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={168}>7 days · more history</option></select></label><label className="ws-checkbox"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/> Auto-check every 10 min</label><button className="ws-button primary" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={15} className={loading?'ws-spin':''}/>{loading?'Checking NASA…':'Check for updates'}</button></div>
    <div className="ws-metrics"><div className="ws-metric"><span>Loaded detections</span><strong>{observations.length.toLocaleString()}</strong><small>{mode==='live'?`${hours===168?'7 days':`${hours} hours`} / ${sensor.toUpperCase()}`:'Local dataset'}</small></div><div className="ws-metric"><span>Highest FRP</span><strong>{observations.length?highest.toFixed(1):'—'}<small> MW</small></strong><small>Fire radiative power</small></div><div className="ws-metric"><span>Latest NASA acquisition</span><strong className="ws-date">{time(feed?.latestObservation)}</strong><small>Your local time</small></div><div className="ws-metric"><span>NASA fetched</span><strong className="ws-date">{time(feed?.fetchedAt)}</strong><small>{feed?.stale?'Stale cache':feed?.cached?'10-minute server cache':'Last successful retrieval'}</small></div></div>
    {feed?.warning&&<div className="ws-notice">{feed.warning}</div>}
    <div className="ws-toolbar"><label>Find coordinates / ID<input type="search" placeholder="e.g. 21.14" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Minimum FRP (MW)<input type="number" min="0" step="any" placeholder="All detections" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">Latest acquisition</option><option value="frp">Highest FRP</option></select></label><button className="ws-button" disabled={!visible.length} onClick={()=>downloadText('agnite-observations.csv',exportObservationsCsv(visible),'text/csv;charset=utf-8')}><Download size={15}/> Export {visible.length.toLocaleString()}</button></div>
    <div className="ws-feed-grid"><section className="ws-panel"><div className="ws-panel-head"><h2>Observation map</h2><span className="ws-kicker">{visible.length.toLocaleString()} VISIBLE</span></div><ObservationMap observations={visible} selected={selected} onSelect={choose}/><p className="ws-source">India-region bounds: 6–38° N, 67–99° E; includes neighboring areas. Map outline is generalized. Detections do not establish a fire’s cause.</p></section><section className="ws-panel"><div className="ws-panel-head"><h2>Detection register</h2><span className="ws-kicker">SELECT TO INSPECT</span></div>{visible.length?<><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Location / acquisition</th><th>FRP</th><th>Inspect</th></tr></thead><tbody>{pageRows.map(row=><tr key={row.id} className={selected?.id===row.id?'selected':''}><td><strong>{coord(row)}</strong><small>{time(row.observedAt)}</small></td><td>{row.frp.toFixed(1)}<small>MW</small></td><td><button className="ws-button subtle" onClick={()=>choose(row)} aria-label={`Select ${coord(row)}, ${row.frp} MW`}>{selected?.id===row.id?'Selected':'Select'}</button></td></tr>)}</tbody></table></div><div className="ws-pagination"><button className="ws-button" disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Previous</button><span>{safePage+1} / {totalPages}</span><button className="ws-button" disabled={safePage+1>=totalPages} onClick={()=>setPage(safePage+1)}>Next</button></div></>:<div className="ws-empty">{loading?'Retrieving NASA satellite observations…':observations.length?'No detections match these filters.':feed?'No detections in this source and time window. Try 7 days or another sensor.':'Live observations will appear after NASA responds.'}</div>}
     {selected&&<div className="ws-detail"><span className="ws-kicker">SELECTED DETECTION / {selected.source}</span><h3>{coord(selected)}</h3><p>{selected.frp.toFixed(1)} MW · {selected.brightness?`${selected.brightness} K · `:''}{time(selected.observedAt)}</p><p>{nearby.length} observations within 5 km in the loaded dataset.</p><div className="ws-actions"><button className="ws-button primary" onClick={()=>navigate('analysis')}><BrainCircuit size={15}/> Analyze site</button><button className="ws-button" onClick={()=>navigate('monitoring')}><Bell size={15}/> Monitor</button></div></div>}
    </section></div>
    <p className="ws-source">Source: <a href={feed?.sourceUrl||'https://firms.modaps.eosdis.nasa.gov/active_fire/'} target="_blank" rel="noreferrer">NASA FIRMS public near-real-time downloads ↗</a>. Public feed requires no API key. A ten-minute check does not imply a new satellite acquisition.</p>
   </>}

   {tab==='analysis'&&<AnalysisPanel selected={selected} observations={nearby} context={context} setContext={setContext} report={report} run={run} save={save} demo={loadDemo}/>}
   {tab==='monitoring'&&<>
    <div className="ws-notice">Checks use the loaded NASA feed ({sensor.toUpperCase()}, {hours===168?'7 days':`${hours} hours`}), within 5 km of each saved site. This is in-app monitoring; no background notifications or emails are sent.</div>
    <div className="ws-two-col"><section className="ws-panel"><h2>Add selected location</h2>{selected?<><p className="ws-coordinate">{coord(selected)} · {selected.source}</p><form className="ws-form" onSubmit={addWatch}><label className="ws-full">Site name<input required maxLength={80} placeholder="e.g. Nagpur site 01" value={watchName} onChange={e=>setWatchName(e.target.value)}/></label><label>FRP threshold (MW)<input required type="number" min="0" max="1000000" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><div className="ws-full"><button className="ws-button primary" type="submit"><Bell size={15}/> Save monitored site</button></div></form></>:<div className="ws-empty">Select a detection on the satellite feed first.<button className="ws-button" onClick={()=>navigate('feed')}>Open feed</button></div>}</section><section className="ws-panel"><h2>Feed status</h2><p>Last retrieval: {time(feed?.fetchedAt)}<br/>Latest acquisition: {time(feed?.latestObservation)}</p><p>{feed?.stale||error?'Feed freshness is degraded. Matches below may come from previously loaded data.':feed?'Matches are evaluated against the last successfully loaded observations.':'Waiting for a successful NASA feed retrieval.'}</p><button className="ws-button" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={15}/> Check NASA updates</button></section></div>
    <section className="ws-panel"><div className="ws-panel-head"><h2>Monitored sites</h2><span className="ws-kicker">{watches.length} / 50 SITES</span></div>{alerts.length?<div className="ws-list">{alerts.map(({watch,matches})=><article className="ws-list-item" key={watch.id}><div><h3>{watch.name}</h3><p>{coord(watch)} · threshold ≥ {watch.threshold} MW</p><span className={`ws-status ${matches.length?'warning':''}`}>{!feed?'Awaiting NASA data':`${matches.length} matching detections${feed.stale||error?' · stale feed':''}`}</span>{matches.length>0&&<p>Highest {Math.max(...matches.map(row=>row.frp)).toFixed(1)} MW · latest {time(matches.reduce((latest,row)=>row.observedAt>latest?row.observedAt:latest,''))}</p>}</div><div className="ws-actions">{matches.length>0&&<button className="ws-button" onClick={()=>{setMode('live');choose(matches[0]);navigate('analysis');}}>Inspect</button>}<button className="ws-button" aria-label={`Remove ${watch.name}`} onClick={()=>removeWatch(watch)}><Trash2 size={16}/></button></div></article>)}</div>:<div className="ws-empty">Save a site to start checking nearby NASA detections.</div>}</section>
   </>}
   {tab==='history'&&<section className="ws-panel"><div className="ws-panel-head"><h2>Analysis archive</h2><span className="ws-kicker">{reports.length} / 50 REPORTS</span></div>{reports.length?<div className="ws-list">{reports.map(item=><article className="ws-list-item" key={item.id}><div><span className="ws-kicker">{time(item.createdAt)} / {[...new Set((item.observations??[]).map(row=>row.source))].join(', ')||'saved snapshot'}</span><h3>{item.classification}</h3><p>{item.label} · risk index {item.risk}/100</p><p>{item.summary}</p><details><summary>Saved evidence</summary><ul className="ws-warning-list">{item.report.evidence?.map(evidence=><li key={evidence.label}>{evidence.label}: {evidence.value} — {evidence.detail}</li>)}</ul></details></div><div className="ws-actions"><button className="ws-button" onClick={()=>downloadText(`agnite-report-${item.id}.json`,JSON.stringify(item,null,2))}><Download size={15}/> JSON</button><button className="ws-button" aria-label={`Delete report ${item.label} saved ${time(item.createdAt)}`} onClick={()=>removeReport(item)}><Trash2 size={16}/></button></div></article>)}</div>:<div className="ws-empty">No saved reports yet. Run a site analysis and select “Save report”.<button className="ws-button" onClick={()=>navigate('analysis')}>Open AGNITE AI</button></div>}<p className="ws-source">Up to 50 reports are retained locally. Export JSON for a portable copy. Clearing browser storage removes this archive.</p></section>}
   {tab==='import'&&<div className="ws-two-col"><section className="ws-panel"><h2>Import observations</h2><p>NASA FIRMS CSV or AGNITE columns: latitude, longitude, observedAt, frp. Optional: id, brightness, source. Maximum 5,000 records / 2 MB.</p><label className="ws-file">Choose CSV<input type="file" accept=".csv,text/csv" onChange={e=>void importFile(e.target.files?.[0])}/></label><a className="ws-button" href="/data/thermal-observation-template.csv" download><Download size={15}/> Download demo template</a>{csv&&<div className="ws-detail"><span className="ws-kicker">{fileName}</span><h3>{csv.observations.length} valid observations</h3>{csv.errors.length>0&&<div className="ws-notice error">{csv.errors.length} issue(s). Invalid rows will be skipped.</div>}<ul className="ws-warning-list">{[...csv.errors,...csv.warnings].slice(0,20).map((message,index)=><li key={index}>{message}</li>)}</ul>{csv.errors.length+csv.warnings.length>20&&<p>Showing the first 20 messages.</p>}<button className="ws-button primary" disabled={!csv.observations.length} onClick={()=>{activate(csv.observations);setNotice(`${csv.observations.length} valid observations loaded from ${fileName}.`);navigate('analysis');}}>Use valid observations</button></div>}<p className="ws-source">Uploaded records are labeled imported. Only explicitly marked demo rows retain the simulated label. Importing a file does not authenticate it as a live NASA feed.</p></section>
   <section className="ws-panel"><h2>Add a manual observation</h2><p>Enter measured values. Repeated observations at the same site build a local analysis history.</p><form className="ws-form" onSubmit={manual}><label>Latitude<input name="latitude" type="number" required min="-90" max="90" step="any" placeholder="21.1466"/></label><label>Longitude<input name="longitude" type="number" required min="-180" max="180" step="any" placeholder="79.0889"/></label><label className="ws-full">Acquisition date & time (UTC)<input name="date" type="datetime-local" required/></label><label>FRP (MW)<input name="frp" type="number" required min="0" max="1000000" step="any"/></label><div className="ws-actions ws-full"><button type="submit" className="ws-button primary">Add observation</button><button type="button" className="ws-button" onClick={()=>navigate('analysis')}>Analyze local data</button></div></form><p className="ws-source">Manual entries append to the current non-demo local dataset. They do not modify the NASA feed.</p></section></div>}
   {tab==='assistant'&&<section className="ws-panel"><div className="ws-panel-head"><h2>Ask AGNITE</h2><span className="ws-status">LOCAL COMMAND ASSISTANT</span></div><p>Answers use your loaded dataset and latest analysis. A conversational language model is not connected.</p><div className="ws-actions">{['Highest FRP','Explain classification','What evidence is missing?','Next actions'].map(prompt=><button className="ws-button" key={prompt} onClick={()=>ask(prompt)}>{prompt}</button>)}</div><div className="ws-chat" role="log" aria-label="AGNITE conversation" aria-live="polite">{messages.map((message,index)=><article key={index} className={`ws-message ${message.role}`}><span className="ws-kicker">{message.role==='user'?'YOU':'AGNITE'}</span><p>{message.text}</p></article>)}</div><form className="ws-chat-form" onSubmit={e=>{e.preventDefault();ask(question);}}><label className="sr-only" htmlFor="agnite-question">Ask about the loaded observations</label><input id="agnite-question" maxLength={500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about FRP, evidence, classification or monitoring…"/><button className="ws-button primary" disabled={!question.trim()} type="submit"><Send size={16}/> Ask</button></form></section>}
  </main></div>
 </div>;
}
