"""
Pydantic schemas for alerts generated by monitoring services.
"""

from __future__ import annotations

from typing import List, Literal, Optional
from pydantic import BaseModel, Field

AlertSeverity = Literal["INFO", "LOW", "MODERATE", "HIGH", "CRITICAL"]
AlertType = Literal[
    "NEW_THERMAL_DETECTION",
    "FRP_THRESHOLD_EXCEEDED",
    "SUDDEN_FRP_INCREASE",
    "HIGH_RISK_CLASSIFICATION",
    "PERSISTENT_SOURCE_CHANGE",
]


class AlertResponse(BaseModel):
    """Response model representing a generated alert."""

    id: str
    watch_id: str = Field(..., alias="watchId", serialization_alias="watchId")
    watch_name: Optional[str] = Field(None, alias="watchName", serialization_alias="watchName")
    observation_id: Optional[str] = Field(
        None, alias="observationId", serialization_alias="observationId"
    )
    analysis_id: Optional[str] = Field(
        None, alias="analysisId", serialization_alias="analysisId"
    )
    type: str
    severity: AlertSeverity
    title: str
    message: str
    latitude: float
    longitude: float
    frp: Optional[float] = None
    risk: Optional[int] = None
    confidence: Optional[float] = None
    fingerprint: str
    acknowledged: bool
    created_at: str = Field(..., alias="createdAt", serialization_alias="createdAt")

    model_config = {
        "populate_by_name": True,
        "serialize_by_alias": True,
    }


class AlertListResponse(BaseModel):
    """Paginated list of alerts."""

    alerts: List[AlertResponse]
    total: int
    unacknowledged_count: int = Field(
        ..., alias="unacknowledgedCount", serialization_alias="unacknowledgedCount"
    )

    model_config = {
        "populate_by_name": True,
        "serialize_by_alias": True,
    }
