"""initial_phase4_tables

Revision ID: 5bfba80c71c7
Revises: 
Create Date: 2026-09-13 23:46:21.945746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfba80c71c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('selected_observation_id', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_index', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_coords', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sensor', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frp', sa.Float(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('satellite', sa.String(length=32), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=True),
    sa.Column('daynight', sa.String(length=8), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_external_id'), ['external_id'], unique=False)
        batch_op.create_index('ix_observations_lat_lon', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index('ix_observations_observed_at_frp', ['observed_at', 'frp'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_source'), ['source'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('observations_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)

    op.create_table('watches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('frp_threshold', sa.Float(), nullable=False),
    sa.Column('risk_threshold', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index('ix_watches_coords', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_enabled'), ['enabled'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('watch_id', sa.String(length=64), nullable=False),
    sa.Column('observation_id', sa.String(length=128), nullable=True),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_alerts_watch_ack', ['watch_id', 'acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_watch_id'), ['watch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_watch_id'))
        batch_op.drop_index('ix_alerts_watch_ack')
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_acknowledged'))

    op.drop_table('alerts')
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_enabled'))
        batch_op.drop_index('ix_watches_coords')

    op.drop_table('watches')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_source'))
        batch_op.drop_index('ix_observations_observed_at_frp')
        batch_op.drop_index(batch_op.f('ix_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_observations_longitude'))
        batch_op.drop_index(batch_op.f('ix_observations_latitude'))
        batch_op.drop_index('ix_observations_lat_lon')
        batch_op.drop_index(batch_op.f('ix_observations_external_id'))

    op.drop_table('observations')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index('ix_analyses_coords')

    op.drop_table('analyses')
    # ### end Alembic commands ###
