import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Bell, BrainCircuit, ChevronRight, CircleGauge, CloudSun, Database, Flame, Gauge, Layers3, MapPin, Radio, ShieldCheck, Sparkles, Thermometer, Upload, Waves, Wind, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Hotspot = { id: number; city: string; state: string; type: string; temp: number; normal: number; confidence: number; risk: string; x: number; y: number; color: string; industry: string; land: string };
const hotspots: Hotspot[] = [
  { id: 1, city: 'Jamnagar', state: 'Gujarat', type: 'Industrial Fire', temp: 58.4, normal: 34.1, confidence: 91, risk: 'HIGH', x: 25, y: 47, color: '#ff563d', industry: 'Oil Refinery · 1.3 km', land: 'Industrial' },
  { id: 2, city: 'Nashik', state: 'Maharashtra', type: 'Forest Fire', temp: 46.2, normal: 31.6, confidence: 84, risk: 'MEDIUM', x: 35, y: 57, color: '#ffae35', industry: 'No nearby industry', land: 'Forest edge' },
  { id: 3, city: 'Bengaluru', state: 'Karnataka', type: 'Agricultural Burning', temp: 41.8, normal: 29.9, confidence: 79, risk: 'MEDIUM', x: 48, y: 76, color: '#b989ff', industry: 'Grain processing · 4.8 km', land: 'Agricultural' },
  { id: 4, city: 'Kolkata', state: 'West Bengal', type: 'Gas Flare', temp: 39.7, normal: 33.2, confidence: 88, risk: 'LOW', x: 72, y: 55, color: '#58d8ca', industry: 'Gas terminal · 2.1 km', land: 'Industrial' },
  { id: 5, city: 'Dehradun', state: 'Uttarakhand', type: 'Unknown', temp: 35.1, normal: 30.8, confidence: 62, risk: 'LOW', x: 51, y: 19, color: '#ecdf52', industry: 'No nearby industry', land: 'Mixed woodland' },
];
const chartData = [{ time: '12:00', value: 33 }, { time: '14:00', value: 35 }, { time: '15:00', value: 38 }, { time: '16:00', value: 44 }, { time: '17:00', value: 58 }, { time: '18:00', value: 55 }];
const fade = { hidden: { opacity: 0, y: 16 }, show: { opacity: 1, y: 0, transition: { duration: .55 } } };

function App() {
  const [selected, setSelected] = useState(hotspots[0]);
  const [showPanel, setShowPanel] = useState(true);
  const [activeTab, setActiveTab] = useState('Detect Today');
  return <main className="shell">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="topbar"><div className="brand"><div className="brand-mark"><Flame size={22} fill="currentColor" /></div><div><strong>Agnite</strong><span>FIRE INTELLIGENCE PLATFORM</span></div></div><div className="signal"><span className="live-dot" /> LIVE SATELLITE FEED <span className="divider" /> 08 SEP 2026 · 18:42 IST</div><button className="icon-btn" title="Notifications"><Bell size={18} /></button><div className="avatar">SI</div></header>
    <motion.section className="hero" initial="hidden" animate="show" variants={fade}><div><p className="eyebrow"><Radio size={14} /> NATIONAL SITUATIONAL AWARENESS</p><h1>From satellite signals<br /><em>to smarter decisions.</em></h1><p className="hero-copy">A live intelligence layer for detecting, understanding, and preventing fire risk across India.</p></div><div className="workflow">{['Detect','Understand','Explain','Predict','Prevent'].map((item, i) => <div className={i === 0 ? 'step active' : 'step'} key={item}><span>0{i + 1}</span>{item}{i < 4 && <ChevronRight size={14} />}</div>)}</div></motion.section>
    <section className="metrics"><Metric icon={<Flame />} label="ACTIVE HOTSPOTS" value="24" trend="+6.2%" tone="orange" /><Metric icon={<Thermometer />} label="PEAK DEVIATION" value="+24.3°" trend="Jamnagar, GJ" tone="red" /><Metric icon={<ShieldCheck />} label="RISK FORECAST" value="HIGH" trend="Next 2–4 weeks" tone="green" /><Metric icon={<Database />} label="DATA FRESHNESS" value="04m 12s" trend="NASA FIRMS · MODIS" tone="cyan" /></section>
    <div className="workspace"><motion.section className="map-card panel" initial="hidden" animate="show" variants={fade} transition={{ delay: .1 }}><div className="panel-heading"><div><p className="eyebrow">01 · DETECT</p><h2>Live hotspot map</h2></div><div className="map-actions"><button className="small-btn"><Layers3 size={14} /> Layers</button><button className="small-btn"><CloudSun size={14} /> Satellite</button></div></div><div className="map"><div className="map-grid" /><div className="india-shape"><span>INDIA</span></div>{hotspots.map(h => <button key={h.id} className={'hotspot ' + (selected.id === h.id ? 'selected' : '')} style={{ left: h.x + '%', top: h.y + '%' }} onClick={() => { setSelected(h); setShowPanel(true); }} title={'Select ' + h.city}><i style={{ background: h.color, boxShadow: `0 0 18px ${h.color}` }} /><b>{h.id}</b></button>)}<div className="map-label label-west">ARABIAN SEA</div><div className="map-label label-east">BAY OF BENGAL</div><div className="map-legend">{['Industrial Fire','Gas Flare','Forest Fire','Agricultural Burning'].map((x, i) => <span key={x}><i className={'legend-dot c' + i} />{x}</span>)}</div><div className="map-scale">1,000 km <span /></div></div></motion.section>
      <AnimatePresence mode="wait">{showPanel && <motion.aside className="detail panel" key={selected.id} initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 24 }}><div className="panel-heading"><div><p className="eyebrow">02 · UNDERSTAND</p><h2>Hotspot intelligence</h2></div><button className="icon-btn" onClick={() => setShowPanel(false)} title="Close detail panel"><X size={17} /></button></div><div className="location"><div className="location-icon"><MapPin size={18} /></div><div><h3>{selected.city}, {selected.state}</h3><p>Detected 07 Sep 2026, 18:42 IST</p></div><span className="risk high">{selected.risk}</span></div><div className="temp-hero"><div><span>Current temperature</span><strong>{selected.temp}°C</strong></div><div className="delta"><ArrowUpRight size={17} /> +{(selected.temp - selected.normal).toFixed(1)}°C<br /><small>vs normal</small></div></div><div className="detail-grid"><Detail label="Normal temperature" value={`${selected.normal}°C`} icon={<Thermometer />} /><Detail label="AI classification" value={selected.type} icon={<BrainCircuit />} /><Detail label="Nearby industry" value={selected.industry} icon={<Database />} /><Detail label="Land type" value={selected.land} icon={<MapPin />} /></div><div className="confidence"><div><span>Model confidence</span><b>{selected.confidence}%</b></div><div className="progress"><span style={{ width: selected.confidence + '%' }} /></div></div><button className="primary-btn" onClick={() => setActiveTab('Explain')}><Sparkles size={16} /> Explain this event <ArrowUpRight size={15} /></button></motion.aside>}</AnimatePresence>
    </div>
    <section className="lower-grid"><motion.div className="panel chart-panel" initial="hidden" animate="show" variants={fade} transition={{ delay: .2 }}><div className="panel-heading"><div><p className="eyebrow">03 · EXPLAIN</p><h2>Temperature anomaly</h2></div><span className="mini-status"><span className="live-dot" /> ANALYZING</span></div><div className="chart-caption"><strong>+24.3°C</strong><span>deviation from local normal</span></div><ResponsiveContainer width="100%" height={158}><AreaChart data={chartData}><defs><linearGradient id="heat" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff6b4a" stopOpacity={.42} /><stop offset="100%" stopColor="#ff6b4a" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#20384c" vertical={false} /><XAxis dataKey="time" stroke="#668197" tickLine={false} axisLine={false} fontSize={10} /><YAxis stroke="#668197" tickLine={false} axisLine={false} fontSize={10} unit="°" /><Tooltip contentStyle={{ background: '#102538', border: '1px solid #33516a', borderRadius: 8 }} /><Area type="monotone" dataKey="value" stroke="#ff6b4a" strokeWidth={3} fill="url(#heat)" /></AreaChart></ResponsiveContainer></motion.div><motion.div className="panel timeline-panel" initial="hidden" animate="show" variants={fade} transition={{ delay: .28 }}><div className="panel-heading"><div><p className="eyebrow">04 · LEARN</p><h2>Historical fire timeline</h2></div><span className="year">2026</span></div><div className="timeline">{[['2019','Gas flare','47°C'],['2021','Industrial heat','51°C'],['2023','Industrial fire','61°C'],['2025','Thermal anomaly','54°C'],['2026','Current event','58.4°C']].map((row, i) => <div className={'timeline-row ' + (i === 4 ? 'current' : '')} key={row[0]}><b>{row[0]}</b><span className="timeline-dot" /><div><strong>{row[1]}</strong><small>{row[2]}</small></div></div>)}</div><p className="timeline-note"><Activity size={15} /> 7 previous incidents · frequency change <b>+34%</b></p></motion.div><motion.div className="panel forecast-panel" initial="hidden" animate="show" variants={fade} transition={{ delay: .36 }}><div className="panel-heading"><div><p className="eyebrow">05 · PREDICT</p><h2>Future risk</h2></div><Gauge size={20} color="#79e2cf" /></div><div className="score"><div className="score-ring"><strong>78</strong><span>/100</span></div><div><b>Risk score</b><p>Next 2–4 weeks</p></div></div><div className="forecast-list"><div><span>Next 24 hours</span><b className="low">LOW</b></div><div><span>Next 7 days</span><b className="medium">MEDIUM</b></div><div><span>Next 30 days</span><b className="high">HIGH</b></div></div><button className="primary-btn ghost" onClick={() => setActiveTab('Prevent')}><ShieldCheck size={16} /> View recommendations</button></motion.div></section>
    <footer><div className="footer-brand"><Flame size={17} fill="currentColor" /><span>AGNITE <small>SIH26162</small></span></div><nav>{['Detect Today','Learn from the Past','Predict Smarter','Prevent Together'].map((tab, i) => <button className={activeTab === tab ? 'active' : ''} onClick={() => setActiveTab(tab)} key={tab}>{[<Radio />, <BarChart3 />, <Waves />, <ShieldCheck />][i]} {tab}</button>)}</nav><div className="system"><span className="live-dot" /> ALL SYSTEMS NOMINAL</div></footer>
  </main>;
}
function Metric({ icon, label, value, trend, tone }: { icon: React.ReactNode; label: string; value: string; trend: string; tone: string }) { return <div className="metric"><div className={'metric-icon ' + tone}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{trend}</small></div></div> }
function Detail({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="detail-item"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div> }
export default App;
